/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as BotyRouteImport } from './routes/boty'
import { Route as IndexRouteImport } from './routes/index'

const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const BotyRoute = BotyRouteImport.update({
  id: '/boty',
  path: '/boty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boty': typeof BotyRoute
  '/kontakt': typeof KontaktRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boty': typeof BotyRoute
  '/kontakt': typeof KontaktRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boty': typeof BotyRoute
  '/kontakt': typeof KontaktRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boty' | '/kontakt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boty' | '/kontakt'
  id: '__root__' | '/' | '/boty' | '/kontakt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotyRoute: typeof BotyRoute
  KontaktRoute: typeof KontaktRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boty': {
      id: '/boty'
      path: '/boty'
      fullPath: '/boty'
      preLoaderRoute: typeof BotyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotyRoute: BotyRoute,
  KontaktRoute: KontaktRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
